### ISSUE TITLE
Provider versions not found in Terraform registry

### ISSUE THREAD

**Issue by xaevman** [yugabyte/terraform-provider-ybm#19]
I can't seem to actually init your provider via the terraform registry. It complains about an Incompatible provider version. Am I doing something wrong?

```
│ Error: Incompatible provider version
│ 
│ No compatible versions of provider registry.terraform.io/yugabyte/ybm were found.
```

On terraform 1.0.1 and have tried the following incantations...
```
terraform {
  required_providers {
    ybm = {
      source  = "yugabyte/ybm"
      version = "0.1.0"
    }
  }
}
```

```
terraform {
  required_providers {
    ybm = {
      source  = "yugabyte/ybm"
      version = "~> 0.1.0"
    }
  }
}
```

This one is copied straight from the Terraform registry page for the provider but also fails: https://registry.terraform.io/providers/yugabyte/ybm/latest
```
terraform {
  required_providers {
    ybm = {
      source = "yugabyte/ybm"
      version = "0.1.1-pre.1"
    }
  }
}
```

**Comment by cdavid** [comment]
Hi

Can you please try updating the terraform version to something more recent and let us know if that works for you? I believe such an old version of TF (more than a year old at this point: https://github.com/hashicorp/terraform/releases/tag/v1.0.1 ) might be incompatible with the provider.

Thanks!

**Comment by xaevman** [comment]
Ahh, yeah. It worked in 1.2.7. I guess I had interpreted the provider configuration blurb on the registry page to be saying that this should be supported on 0.13+ 

![image](https://user-images.githubusercontent.com/3894743/190210734-0898d77d-f494-4f8f-8df8-cb9bd466040a.png)

**Comment by cdavid** [comment]
@xaevman  Awesome, glad I could help, please let me know if I can help with anything or if you hit any issues.
