### ISSUE TITLE
backup_schedules - cron issue

### ISSUE THREAD

**Issue by brianmjones** [yugabyte/terraform-provider-ybm#20]
can't get cron_expression working in backup_schedules for resource ybm_cluster

it completes successfully according to terraform, but when I go to the yugabyte backup tab for the cluster, the screen just hangs.

resource "ybm_cluster" "single_region_cluster" {
  cluster_name = "single-region-cluster2"
  cloud_type   = "GCP"
  cluster_type = "SYNCHRONOUS"
  cluster_region_info = [
    {
      region    = "us-west2"
      num_nodes = 1
    }
  ]
  cluster_tier           = "PAID"
  fault_tolerance        = "NONE"
  node_config = {
    num_cores    = 4
    memory_mb    = 15360
    disk_size_gb = 200
  }
  backup_schedules = [
    {
      state                    = "ACTIVE"
       cron_expression = "30 14 * * *" 
      retention_period_in_days = 10
    }
  ]

**Comment by brianmjones** [comment]
terraform {
  required_providers {
    ybm = {
      source = "yugabyte/ybm"
      version = "0.1.1-pre.2"
    }
  }
}

**Comment by cdavid** [comment]
Thanks for trying out the provider. I have filed a bug against our UI layer and will update you when it is fixed.

**Comment by cdavid** [comment]
The fix was checked in and should be deployed to production with our next update (likely next week).

**Comment by cdavid** [comment]
The issue should now be fixed.
