### ISSUE TITLE
backup_schedules - backup_description doesn't work

### ISSUE THREAD

**Issue by brianmjones** [yugabyte/terraform-provider-ybm#21]
For a new cluster, 

│ Error: Provider produced inconsistent result after apply
│
│ When applying changes to ybm_cluster.single_region_cluster, provider "provider[\"registry.terraform.io/yugabyte/ybm\"]" produced an unexpected new value: .backup_schedules[0].backup_description: was cty.StringVal("testing backup
│ schedule"), but now cty.StringVal("Default backup schedule for single-region-cluster2").
│
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.

The next apply causes the cluster to be replaced:

Terraform will perform the following actions:

  \# ybm_cluster.single_region_cluster **is tainted, so must be replaced**
-/+ resource "ybm_cluster" "single_region_cluster" {

terraform {
  required_providers {
    ybm = {
      source = "yugabyte/ybm"
      version = "0.1.1-pre.2"
    }
  }
}

resource "ybm_cluster" "single_region_cluster" {
  cluster_name = "single-region-cluster2"
  cloud_type   = "GCP"
  cluster_type = "SYNCHRONOUS"
  cluster_region_info = [
    {
      region    = "us-west2"
      num_nodes = 1
    }
  ]
  cluster_tier           = "PAID"
  fault_tolerance        = "NONE"
  node_config = {
    num_cores    = 4
    memory_mb    = 15360
    disk_size_gb = 200
  }
  backup_schedules = [
    {
      state                    = "ACTIVE"
      backup_description = "testing backup schedule"
      retention_period_in_days = 10
      time_interval_in_days    = 10
    }
  ]
  credentials = {
    ysql_username = "example_ysql_user"
    ysql_password = var.ysql_password
    ycql_username = "example_ycql_user"
    ycql_password = var.ycql_password
  }

}

**Comment by cdavid** [comment]
Thanks for trying out this provider. I will take a look, triage this issue and see what fix is needed.

**Comment by cdavid** [comment]
Hi @brianmjones - sorry it took such a long time. This has now been fixed in version `0.2.0-pre.5`.
