### ISSUE TITLE
Allow List to Cluster Binding

### ISSUE THREAD

**Issue by jbenassi** [yugabyte/terraform-provider-ybm#76]
When I specify the allow\_list\_name as one of a list(string)  of names to input to the "cluster" resource. The binding does not take place (as shown in the examples). Does it expect the actual ID known after apply that it really needs? If not could you please explain what I am doing wrong? eg:  
  
I create 2 allow\_list resources with names below.

  
cluster\_allow\_list\_ids = \["devops-team", "dev-aws-natgw"\]  which does not seem to make the link/binding to the cluster.

In the example, it shows what appears to be the same?

  
  cluster\_allow\_list\_ids = \["example-allow-list-id-1", "example-allow-list-id-2"\] #Optional  
  fault\_tolerance        = "ZONE"  
  node\_config = {  
    num\_cores    = 2  
    disk\_size\_gb = 50 #Optional  
  }

**Comment by shinji62** [comment]
`"devops-team", "dev-aws-natgw"` these seems to be the name of the allow list not the id. 
We don't have data source yet for allow list, but you can import them into you terraform for now see https://registry.terraform.io/providers/yugabyte/ybm/latest/docs/resources/allow_list#import

I will open a feature request to add the data source as well for allow list

The best is to manage the allow list within terraform as well, then you can get the alllow list id from there
```hcl
resource "ybm_allow_list" "devops-team" {
  allow_list_name        = "devops-team"
  cidr_list              = ["yourip/32"]
  allow_list_description = "devops-team"
}

resource "ybm_allow_list" "dev-aws-natgw" {
  allow_list_name        = "dev-aws-natgw"
  cidr_list              = ["yourip/32"]
  allow_list_description = "devops-team"
}

resource "ybm_cluster" "single_region_cluster" {
....
cluster_allow_list_ids = [ybm_allow_list.devops-team.allow_list_id,ybm_allow_list.dev-aws-natgw.allow_list_id] 
}

```

**Comment by shinji62** [comment]
New provider version have been released adding the data source for allow list.
Please reopen this if needed.
